# Generated by Django 5.1.3 on 2024-12-15 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_company_users_alter_orderdetail_unit_price_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderresult',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='orderresult',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderresult',
            name='result',
            field=models.CharField(max_length=1000),
        ),
    ]
