# Generated by Django 5.1.3 on 2024-12-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttype',
            name='eco',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weighttype',
            name='pre',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weighttype',
            name='std',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
