# Generated by Django 5.1.3 on 2024-12-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_weighttype_eco_alter_weighttype_pre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttype',
            name='eco',
            field=models.DecimalField(decimal_places=15, max_digits=15),
        ),
        migrations.AlterField(
            model_name='weighttype',
            name='pre',
            field=models.DecimalField(decimal_places=15, max_digits=15),
        ),
        migrations.AlterField(
            model_name='weighttype',
            name='std',
            field=models.DecimalField(decimal_places=15, max_digits=15),
        ),
    ]
