# Generated by Django 5.1.3 on 2024-12-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_weighttype_eco_alter_weighttype_pre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='depth',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='height',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='width',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
