# Generated by Django 5.1.3 on 2024-12-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_dimension_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='dimension_type',
            field=models.CharField(default='product', max_length=20),
            preserve_default=False,
        ),
    ]
