# Generated by Django 5.1.3 on 2024-12-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_dimension_created_by_dimension_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='volume',
            field=models.DecimalField(decimal_places=10, editable=False, max_digits=30),
        ),
    ]
